typography_spectrum: 0.39726
color:
  brandColors:
    - '#13262d'
    - '#e2e4cf'
    - '#859997'
    - '#607472'
    - '#714449'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23536
analytics:
  google: null
  facebook: null
  twitter: null
name: Photography by Ben
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 'http://benjaminblue.me'
    url: 'http://benjaminblue.me'
    name: Main Page
    type: external
favicon: null
title: Photography by Ben
purpose: []
